purple-cobras/thesis

- db/db.js
- package.json
Create all schema related games.
> Chore/database (Closes #8)

- client/www/ang/app.js
- client/www/ang/login/login.js
- client/www/ang/main/main.js
- client/www/ang/routes.js
- client/www/index.html
- add angular/fb sdk
- set up fb sdk with app id
- save fb access token upon successful `auth0` login
- when main view loads, query fb api for user's friends connected to the app
- removed reference to `controller.js` and a logging statement
> Feat/fb friends (resolves #21)

- client/bower.json
> (fix) add angular-facebook dependency

- client/www/ang/app.js
- quick fix to prevent an error upon unsuccessful login
> (fix) replace $location with $state

- client/www/ang/login/login.js
- server/routes.js
- save name and fb profile pic url to db upon signin
> Feat/auth name (resolves #51)

- db/migrations/20160312142550_add_creator_id_to_games.js
- db/models.js
- add `creator_id` to `games` table
- specify `creator` relationship in `Game` model
> (feat) add creator to db schema and model

- client/www/ang/main/main.html
- client/www/ang/main/main.js
- client/www/ang/newGame/newGame.html
- client/www/ang/newGame/newGame.js
> (chore) Disables button so users cannot create multiple games at once

- client/www/ang/game/game.html
- client/www/ang/game/game.js
- when you are in a game view, hitting back now takes you to the main page (instead of new game)
> (fix) override game view's back button to take you to the main page

- client/www/index.html
- client/www/js/appsettings.js
Removed rebase text from index.html
> (chore/fix) code cleanup

- client/bower.json
- client/gulpfile.js
- client/package.json
- client/tests/unit-tests.conf.js
- client/tests/unit-tests/controller-tests.js
Unable to pass controller scope to test. Requires `npm install` and `bower install`.
> (test) Add Karma/Jasmine test runner.

- client/www/ang/login/login.js
- client/www/ang/main/main.html
- client/www/ang/main/main.js
- client/www/ang/newGame/newGame.js
- server/routes.js
- display who invited you to a game
> Feat/invites (resolves #72)

- client/www/ang/game/game.js
- client/www/ang/login/login.js
- client/www/ang/main/main.js
- client/www/ang/newGame/newGame.js
- client/www/ang/services.js
- db/helpers.js
- server/routes.js
- server/sockets.js
> Revert "Chore/remove sockets"

- client/www/ang/main/main.js
Also, commented out all front-end socket
> Back-end accept/decline invite functionality

- client/www/ang/game/game.js
- client/www/ang/login/login.js
- client/www/ang/main/main.js
- client/www/ang/services.js
- db/helpers.js
- db/migrations/20160314142649_add_score_to_users_games.js
- db/models.js
- server/routes.js
- on signin, save the current game id
- on app launch, if there is a current game id, retrieve its info from server
- devise route to retrieve game info
- create helper to grab game info
- refactor game state into its own factory
> Refactor/game state (resolves #104)

- client/www/ang/login/login.js
- client/www/ang/main/main.js
- client/www/ang/services.js
- server/routes.js
- on main screen, check to see if user has a new current game
- if so, load info from that game
- create generic api endpoint for retrieving user info
> Feat/current game patch (resolves #106)

- db/helpers.js
- server/routes.js
- invites are created for game creators and automatically marked as accepted
- players are only included in a game if they have accepted the game
> Fix/invites and players (resolves #116)

- client/www/ang/game/game.html
- client/www/ang/services.js
- db/helpers.js
- server/sockets.js
- when a game starts, kick off the first round
- include reader info in rounds array
- process rounds on client and display in UI
> (feat) rounds first pass

- client/www/ang/game/game.html
- client/www/ang/game/game.js
- client/www/ang/services.js
- db/helpers.js
- server/routes.js
- server/sockets.js
- users can submit responses
- responses are pushed to all other clients
- when game info is sent to a client, it now contains all rounds and responses
> Feat/responses (resolves #142 resolves #144 resolves #143)

- client/www/ang/services.js
- fix to socket listener for updating the a player's score when a correct guess is made
> (fix) update scores via socket events when a correct guess is made (resolves #174)

- server/sockets.js
- refactor `online` object to store an array of socket info so that multiple clients can be connected as the same user
- refactor socket emitters that go to a specific user to go to all sockets for that user
> Feat/enable sockets multi device (resolves #172)

- client/scss/ionic.app.scss
- client/www/ang/login/login.html
- client/www/ang/login/login.js
- db/db.js
- db/helpers.js
- db/migrations/20160317221258_add_timestamp_to_users.js
- package.json
- server/routes.js
Includes db migration.
Refactor profile code in login.js to use Auth0 store.
Todo: Increment "games played" count in app upon game completion. Data does not currently refresh after initial login.
> (feat) Add user profile data to signin (resolves #180)

- client/bower.json
- client/www/ang/app.js
- client/www/ang/game/game.js
- client/www/ang/main/main.js
- client/www/ang/newGame/newGame.js
- client/www/index.html
- db/helpers.js
- server/sockets.js
On start of a game:
Backend: Unresolved (null) invites will be set to rejected (2)
Frontend: Socket event will trigger getInvitations() for each connected player with an effected invite.  Player will be alerted of missed invite via ionic-toast
> Feat/resolve dangling invite (resolves #160) (resolves #187)

- client/www/ang/game/game.html
- make responses word wrap when necessary
> (fix) make responses and player names word wrap if necessary

- client/www/ang/game/game.html
- client/www/ang/services.js
- guess results show up in toasts instead of where the guesser name is held
> (feat) guess results are now shown in toasts

- client/.gitignore
- client/www/ang/login/login.html
- client/www/ang/login/login.js
- db/helpers.js
- server/routes.js
- Add higher res profile pic.
- Refactor profile log to be more modular.
> Refactor/profile pic (resolves #169)

- client/.gitignore
- db/helpers.js
- don't allow reader to be the first guesser
- remove css from `.gitignore`
> Feat/reader no guess first (resolves #168)

- client/www/ang/game/game.html
- client/www/ang/services.js
- fixes logic for front-end guess processing, which affected when notifications showed up and score updates
> Fix/device testing (resolves #197)

- db/helpers.js
- the first guesser is the person who is next to the reader in the players array. this prevents the same person from guessing first every time
> Fix/guesser assignment (resolves #199)

- client/scss/ionic.app.scss
- client/www/ang/game/game.html
- client/www/ang/login/login.js
- client/www/ang/services.js
- Adds Ionic card element for Topic display, Reader status. Card turns yellow for Reader only when pending topic submission.
- Tested in labs and emulator.
> (Feat) Add reader/topic card element to top of Game screen (resolves #192)

- client/www/ang/game/game.html
- client/www/ang/main/main.js
- client/www/ang/services.js
- db/helpers.js
- db/migrations/20160319132535_add_completed_to_games.js
- db/migrations/20160319140853_add_winner_id_to_games.js
- db/models.js
- write winning logic on back end
- upon win, set that in the db as `games.winner_id`, set `games.completed = true`, nullify all players `current_game_id`
- when a client receives a winning event from the socket, update the UI
> Feat/winning (resolves #194)

- client/www/ang/services.js
- db/helpers.js
- db/migrations/20160319123549_skip_if_guessed.js
Adds a skip_if_guessed boolean column to games table and property to Game.game object.  Can refactor to be more generic if we add more rules. Helper function setGuesser now properly sets next unguessed guesser if game has skip_if_guessed flagged.
> Feat/skip if guessed (resolves #183)

- client/www/ang/game/game.js
- refresh game when app becomes active again and you are on the game page
- removed large comment block
> (feat) when app resumes and you are on the game page, refresh the game

- .gitignore
- client/www/ang/game/game.js
- client/www/ang/services.js
- client/www/js/appsettings.js
- db/helpers.js
***Closed two PR and joined into one***  
Replaced Array.find -> return indexOf() with for loop returning i(ndex).  
***Also:***  
Increases newScore by 2 on user_game if end of round, also increases front end score by two
NOTE Initially had helper logic @ 591 more closely scoped to new round around 611. But, kept moving higher up before realizing that the front end score was manipulated seperately from the saved score. Can refactor if needed.
> Refactor/eliminate find (resolves #226)  Feat/add one if last (resolves #227)

- client/www/ang/game/game.html
- client/www/ang/services.js
- client/www/js/appsettings.js
Disables submit topic and submit guess duplicate submission.
> Fix/disable double tap (resolves #233) (resolves #234)

- client/config.xml
- client/ionic.project
- client/www/ang/game/game.js
- client/www/ang/main/main.js
- add crosswalk to android (this runs the app within a chrome web view, not the default android browser)
- crosswalk fixes the voice issues on android
- only resume reading responses if you are the reader
> Fix/android voice (resolves #241)

- client/package.json
- client/www/ang/app.js
- client/www/ang/game/game.js
- client/www/ang/main/main.js
- add empty calls to responsiveVoice so that it works later
- specify version of ionic keyboard plugin (so as to not allow keyboard status bar to show)
> (fix) voice

- client/scss/ionic.app.scss
- client/www/ang/game/game.html
- client/www/ang/login/login.js
- client/www/ang/services.js
- client/www/js/appsettings.js
- When topic is set, user notified through toast popup and topic animation.
- Refactored setProfile so profile loads on app reload.
> Feat/topic notif (closes #229)

- client/config.xml
- only speak empty string if voice not already playing
- update version in `config.xml`
> (fix) actually fix voice issues on android

- client/www/ang/game/game.js
- client/www/ang/main/main.js
- actually fix it but for real this time
> (fix) actually fix it this time but for real this time

- client/www/ang/game/game.js
- scroll up the view when a response/topic extends another line
> (feat) scroll up when response/topic gets one line longer

- client/www/ang/game/game.js
- client/www/ang/main/main.js
- client/www/js/appsettings.js
Reverse voice playing conditionals. Change appsettings back to dev environment.
> (fix) Voice conditionals

- client/gulpfile.js
- client/package.json
- karma.conf.js
Also adjust karma.conf to include elastic file src
Add jsHint to gulp. Run with gulp lint. Resolves #43
> Allows karma to run with gulp test

- client/www/ang/game/game.html
- client/www/ang/login/login.html
- client/www/ang/login/login.js
- client/www/css/ionic.app.css
- db/helpers.js
- server/routes.js
Display win count on profile. Refactor db queries for profile data.
> Feat/profile wins (resolves #263)

- client/www/ang/game/game.html
- client/www/ang/login/login.js
- db/migrations/20160322003453_add_topic_saved_to_users_rounds.js
- db/migrations/20160322181836_index_saved_column_in_users_rounds.js
- add migrations from reverted PR to prevent migration directory corruption
- style "You need at least one friend to join"
> (chore) migrations/styles

- client/www/ang/app.js
- db/helpers.js
- db/migrations/20160324132233_add_ai_flag_to_users.js
- db/migrations/20160324132720_add_alchemy_attrs_to_responses.js
- research/AI.md
- create AI flag for users
- create helper to get AI player
- create alchemy columns in responses table
- change game name to `Black Mamba`
> Chore/ai db (resolves #299)

- package.json
- server/alchemy.js
- create function to make api calls to alchemy
- takes in the text we are querying, and an options object, which should have an error and success callback
> (chore) alchemy calls

- db/migrations/20160324174115_add_ai_to_games.js
> (chore) add ai rule to games

- client/scss/ionic.app.scss
- client/www/ang/directives.js
- client/www/ang/game/game.html
- client/www/ang/game/game.js
- client/www/ang/services.js
- db/helpers.js
- server/routes.js
- server/sockets.js
Refactors reverted save/load/random PR.  Combines buttons into Options button w/popup. Button will only appear to reader.  Popup requires abbreviated titles (rand, load, save, back).  Load modal will not open unless saved exist.  Load modal exits on any click.
> Feat/save load rand - resolve #289

- client/scss/ionic.app.scss
- client/www/ang/directives.js
- client/www/ang/game/game.html
- client/www/ang/game/game.js
- client/www/ang/services.js
- db/helpers.js
- server/routes.js
- server/sockets.js
Ending a game will no longer have remove game on initial state change to main
> Fix/end game - resolves #315

- client/scss/ionic.app.scss
- client/www/ang/directives.js
- client/www/ang/game/game.html
- client/www/ang/game/game.js
- client/www/ang/newGame/newGame.html
- client/www/ang/newGame/newGame.js
- client/www/ang/services.js
- db/helpers.js
- db/migrations/20160324193140_add_voice_column_to_game_table.js
Voice optional with new game toggle.  Save topic now a toggle instead of button in options, options popup now block styled allowing for one button per row.
> Feat/optional voice && Refactor/saveLoadRandom - resolves #276 resolves #319

- client/www/ang/game/game.js
- client/www/ang/newGame/newGame.html
- client/www/ang/newGame/newGame.js
- client/www/ang/services.js
- db/helpers.js
- db/models.js
- package.json
- server/sockets.js
Reverts purple-cobras/thesis#323
- chasing down a bug
> Revert "Feat/ai guess"

- client/www/ang/game/game.js
- client/www/ang/newGame/newGame.html
- client/www/ang/newGame/newGame.js
- client/www/ang/services.js
- db/helpers.js
- db/models.js
- package.json
- server/sockets.js
Reverts purple-cobras/thesis#325
> Revert "Revert "Feat/ai guess""

- client/www/ang/main/main.js
- client/www/ang/services.js
- db/helpers.js
- server/sockets.js
If all human invites are declined, complete game, set creator current game to null, toast creator for not having any friends, and set state to main.
> Feat/kick if all decline - resolves #320

- CONTRIBUTING.md
- README.md
- rules.md
- update readme
- overhaul rules
- tweak contributing doc
> Chore/readme rules contrib (resolves #293)

- client/bower.json
- client/www/index.html
- karma.conf.js
Fix to circle Ci requiring ngCookies for other modules loaded.
> (chore) Adds ngCookies to dependencies

- client/config.xml
- `blackmamba` => `Black Mamba`
> (chore) stylize app name

- appsettings.js
- client/www/ang/game/game.html
- client/www/ang/game/game.js
- client/www/ang/newGame/newGame.html
- client/www/ang/newGame/newGame.js
- client/www/ang/services.js
Add appsettings.js "min_players: 3" for prod and test.  Other wise default to 2.  Check against min_players as needed, taking AI into account when kicking game off.  TODO: Fix "You need at least one friend to join"
> Feat/min players - Resolves #287, resolves #311

- client/www/ang/game/game.html
TODO: fix logic on this element's `ng-if`
> (fix) change message when not enough friends have joined

- db/helpers.js
- db/migrations/20160325175701_create_users_devices_table.js
- db/migrations/20160329123033_add_index_for_device_token.js
- server/routes.js
- index `device_token`
- when a user signs in with an existing `device_token`, update that record rather than creating a new one
> Fix/device token (resolves #373)

- server/routes.js
- can no longer load the app through a web browser (excluding ionic serve)
> (fix) make the server api only

- client/www/ang/game/game.html
- db/helpers.js
- show spinner and slightly different message when it's ai's turn
> Feat/ai guessing ui (resolves #386)

- db/helpers.js
- if there is one more guess remaining, ai doesn't have to make it. round ends
> (feat) do not require ai to guess last guess when it is obvious

- client/www/ang/login/login.js
- useful for when the server unexpectedly restarts
> (feat) auto rejoin game sockets (resolves #395)

- db/helpers.js
Fixes issue with AI player unfair advantage.
> (fix) Excludes current round responses from training data.

- client/www/ang/game/game.html
> (chore) change nav title of game view
